### ISSUE TITLE
Allow IdP registration and RPs to match on a "type"

### ISSUE THREAD

**Issue by aaronpk** [w3c-fedid/idp-registration#1]
IdP registration opens up a whole new world of possibilities. However that world is very large. For the bubbles of RPs/IdPs that aren't explicit OpenID Federations, there are still bubbles defined by which protocols the RP/IdP pair can speak, even though they don't have preexisting relationships or any trust roots. For example, webmention.io expects to be able to speak IndieAuth through FedCM, and wouldn't work if you had registered a SAML IdP in the browser.

Concretely, if a user had registered a SAML provider as an IdP in the browser, it would lead to a dead end if they landed on webmention.io and the account popped up in the chooser.

The solution could be as simple as allowing arbitrary strings in a "type" property, and letting IdPs register as being able to handle that type in the register call:

<pre>
IdentityProvider.register({configURL: 'https://authorization-server.com/fedcm/config.php', type: ['indieauth']});
</pre>

Then RPs could ask for IdPs with a matching type:

<pre>
    const identityCredential = await navigator.credentials.get({
      identity: {
        context: "signin",
        providers: [
          {
            type: "indieauth",
            clientId: window.location.origin+"/"
          },
        ],
        // mode: "button"
      },
    }).catch(e => {
      console.log("Error", e.message);
    });
</pre>

This would avoid IdPs showing up in the list when they would be unable to complete an exchange with an RP.

**Comment by aaronpk** [comment]
Right now if you send `type: "X"` and there is no registered IdP of that type, the JS gets an exception `NetworkError: Error retrieving a token` and in the console I see 

> The requested IdP type did not match the registered IdP.

I don't think this case should raise an exception, since it is the same scenario in which there are no IdPs registered at all. The RP asked for IdPs of a certain type, there were none, so nothing can proceed. This is true whether or not there are IdPs of other types registered.

(Also the error message implies only a single IdP can be registered which is also misleading)

**Comment by npm1** [comment]
> I don't think this case should raise an exception, since it is the same scenario in which there are no IdPs registered at all. The RP asked for IdPs of a certain type, there were none, so nothing can proceed. This is true whether or not there are IdPs of other types registered.

What should happen if not an exception? Currently an exception is thrown in all failure cases, like when the user cancels the request by closing the dialog, right? 

> (Also the error message implies only a single IdP can be registered which is also misleading)

Fair enough, we can improve the console error message

**Comment by aaronpk** [comment]
Well there's a difference between an error after something has attempted to happen and nothing being possible at all. In particular, I might want to send the user through some path if they encounter a FedCM error after for example clicking their account. But if there are no IdPs available, I want to do nothing. So I need to be able to distinguish between these different error cases. Right now it is all just a generic exception.

**Comment by npm1** [comment]
Hmm ok. We probably do not want to let the RP know right away whether the user has registered an IDP of a given type, for privacy reasons. If we allowed this, it may provide a fingerprinting vector to an attacker (although it would become visible the first time there is a registered provider of the types requested).

But we do allow the RP to know when there was an error after clicking the account. In this case, a different type of error is thrown. It is not yet merged in the spec but hopefully soon, see https://github.com/w3c-fedid/FedCM/pull/498

**Comment by npm1** [comment]
Happy New Year! I just added a parameter in the assertion endpoint to include 'type'. It would be available on Canary in about a day. Though now I am thinking about it, it is possible this needs to actually be an array. This is because once we fix the issue of multiple 'any' configs passed, there may be multiple matches from the types requested with the types supported by the IdP. In this case I think we would just pass all of these types and the IdP would have to choose one perhaps?

**Comment by npm1** [comment]
Hmm actually, looking at the IdentityProvider dictionary, it seems quite complicated to allow multiple "any" values and multiple matches. This is because there are a bunch of other values and there could be conflicts between them. For example, if there is an IdP matching on two types, but they use different loginHints, what would happen? This leads me to believe that having a single "any" provider is more correct and if needed we can augment it to support passing multiple types there. For the MVP this is probably not needed, what do people think?

**Comment by wseltzer** [comment]
Discussed at 11 April meeting [notes](https://github.com/w3c-fedid/meetings/blob/main/2025/2024-04-11-hybrid-notes.md).

**Comment by togamid** [comment]
Hi, a clarifying questions because I couldn't find any actual specification anywhere: Is the version that got implemented in Chrome sending the type of the IdP as part of the response to the config endpoint or setting it with the `IdentityProvider.register()` call? Both options were discussed in this thread.
Thanks!

**Comment by npm1** [comment]
> Hi, a clarifying questions because I couldn't find any actual specification anywhere: Is the version that got implemented in Chrome sending the type of the IdP as part of the response to the config endpoint or setting it with the `IdentityProvider.register()` call?

In our prototype, the `type` is in the config endpoint.

**Comment by hlflanagan** [comment]
Discussed [28 October 2025](https://github.com/w3c-fedid/meetings/blob/main/2025/2025-10-28-FedCM-notes.md)

**Comment by gobengo** [comment]
@samuelgoto @npm1 Should the rp side of this work in Chrome when I have idp-registration enabled there? 

`IdentityProvider.register()` seems to work, but not
```
const optionsToGetByType = { identity: { providers: [{ type: 'indieauth' }] } }
navigator.credentials.get(optionsToGetByType)
```

Stack (tl;dr it says it wants a `configURL`)
```
idp-registration-rp.ts:105 navigator.credentials.get error TypeError: Failed to execute 'get' on 'CredentialsContainer': Failed to read the 'identity' property from 'CredentialRequestOptions': Failed to read the 'providers' property from 'IdentityCredentialRequestOptions': Failed to read the 'configURL' property from 'IdentityProviderConfig': Required member is undefined.
    at doCredentialRequest (idp-registration-rp.ts:51:52)
    at requestCredential (idp-registration-rp.ts:27:9)
    at HTMLDocument.<anonymous> (idp-registration-rp.ts:127:3)
```

(I'm on localhost. Again, I was able to do IdentityProvider.register once I enabled it in chrome settings, but not yet able to get by type without an immediate TypeError about my `CredentialRequestOptions` missing configURL)
